{
  "hash": "4350221f17713bc37a33c8ed23a499fc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Probability Distributions\"\nsubtitle: \"What They Mean, How to Use Them\"\ndate: 2023-09-14\ncategories: [probability]\ndescription: |\n  Primer on probability distribution I frequently encounter.\nformat:\n  html:\n    code-fold: show\n\n---\n\n\n\n\n\n\n# Random Variables and Distributions\n\nConsider two random variables, $x$ and $y$, with corresponding probability density functions (PDF), $f(x)$ and $f(y)$. Two properties apply to a PDF: $f(x) \\ge 0$ for all $x$, and $\\int_{-\\infty}^{\\infty} f(x) dx = 1$. Also,\n\n- The cumulative density function (CDF) is $F(x) = \\int_{-\\infty}^{\\infty} f(x) dx$.\n- The joint distribution of $x$ and $y$ is $f(x, y) = f(x|y)f(y) = f(y|x)f(x)$ where $f(x|y)$ is called the _conditional PDF_.\n- The marginal PDF is $f(x) = \\int_{-\\infty}^{\\infty} f(x, y) dy$.\n- The chain rule: $f(x_1, x_2, x_3, \\ldots, x_k) = f(x_1| x_2, x_3, \\ldots, x_k) f(x_2 | x_3, \\ldots, x_k) \\cdots f(x_k)$\n\nGiven a distribution function $f(x)$, its integral over the domain of $x$ sums to 1, $\\int {f(x)} dx = 1$. The expected value of random variable $X$ with distribution function $f(x)$ is $E[X] = \\int x \\cdot f(x) dx$. The variance of $x$ is $Var(X) = E[(X - E[X])^2] = \\int x^2 \\cdot f(x) dx$. Alternatively $Var(X) = E[X^2] - E[X]^2$.\n\nFor example, suppose $f(x) = cx^2$, $x \\in [0, 1]$. Then $c = 3$ because $\\int_{x = 0}^1 cx^2 dx = 1$. The expected value of $X$ is $E[X] = \\int_{x = 0}^1 x \\cdot (3x^2) dx = \\frac{3}{4}$. The variance of $X$ is $Var[X] = \\int_{x = 0}^1 (x - \\frac{3}{4})^2 \\cdot (3x^2) dx$ which you can solve for $\\frac{144}{3840} = .0375$. Alternatively, $Var[X] = \\int_{x = 0}^1 x^2 \\cdot (3x^2) dx - \\left(\\frac{3}{4}\\right)^2$ which you can solve for $\\frac{3}{80} = .0375$\n\n## Bernoulli\n\nThe Bernoulli distribution models a single experiment with a binomial outcome. The Bernoulli distribution is a special case of the binomial distribution where a single trial is conducted $(n = 1)$.\n\n>If $X$ is the result of a trial with two outcomes of probability $P(X = 1) = \\pi$ and $P(X = 0) = 1 - \\pi$, then $X$ is a random variable with a Bernoulli distribution  $X \\sim \\mathrm{Bernoulli}(\\pi)$\n>\n>$$f(X = x) = \\pi^x (1 - \\pi)^{1 - x}, \\hspace{1cm} x \\in (0, 1)$$\n>\n>with $E(X) = \\pi$ and $Var(X) = \\pi(1 - \\pi)$.\n\n\n## Binomial\n\nBinomial sampling is used to model counts of one level of a categorical variable over a *fixed sample size*.  \n\n::: {.callout-note}\n### Binomial Distribution\nIf $X$ is the count of successful events in $n$ identical and independent Bernoulli trials of success probability $\\pi$, then $X$ is a random variable with a binomial distribution $X \\sim  \\mathrm{Bin}(n,\\pi)$ \n\n$$\nf(X = k;n, \\pi) = \\frac{n!}{k!(n-k)!} \\pi^k (1-\\pi)^{n-k} \\hspace{1cm} k \\in (0, 1, ..., n), \\hspace{2mm} \\pi \\in [0, 1]\n$$\n\nwith $E(X)=n\\pi$ and $Var(X) = n\\pi(1-\\pi)$.  \n:::\n\nConsider a data set `dat_bin` containing frequencies of high-risk drinkers vs non-high-risk drinkers in a college survey.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_bin <- data.frame(\n  subject = 1:1315,\n  high_risk = factor(c(rep(\"Yes\", 630), rep(\"No\", 685)))\n)\njanitor::tabyl(dat_bin$high_risk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n dat_bin$high_risk   n   percent\n                No 685 0.5209125\n               Yes 630 0.4790875\n```\n\n\n:::\n:::\n\n\nThe MLE of $\\pi$ from the Binomial distribution is the sample mean.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n(p <- mean(dat_bin$high_risk == \"Yes\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4790875\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThere are several ways to calculate a 95% CI for $\\pi$. One method is the normal approximation **Wald** interval.\n\n$$\\pi = p \\pm z_{\\alpha /2} \\sqrt{\\frac{p (1 - p)}{n}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz <- qnorm(.975)\nse <- sqrt(p * (1 - p) / n)\np + c(-z * se, z * se)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4520868 0.5060882\n```\n\n\n:::\n:::\n\n\nThe Wald interval's accuracy suffers when $np<5$ or $n(1-p)<5$ and it does not work at all when $p = 0$ or $p = 1$.  Option two is the **Wilson** method.\n\n$$\\frac{p + \\frac{z^2}{2n}}{1 + \\frac{z^2}{n}} \\pm \\frac{z}{1 + \\frac{z^2}{n}} \\sqrt{\\frac{p(1 - p)}{n} + \\frac{z^2}{4n^2}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nest <- (p + (z^2) / (2 * n)) / (1 + (z^2) / n)\npm <- z / (1 + (z^2) / n) * sqrt(p * (1 - p) / n + (z^2) / (4 * (n^2)))\nest + c(-pm, pm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4521869 0.5061098\n```\n\n\n:::\n:::\n\n\nThis is what `prop.test(correct = FALSE)` calculates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = x, n = n, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  x out of n, null probability 0.5\nX-squared = 2.3004, df = 1, p-value = 0.1293\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.4521869 0.5061098\nsample estimates:\n        p \n0.4790875 \n```\n\n\n:::\n:::\n\n\nThere is a second version of the Wilson interval that applies a \"continuity correction\" that aligns the \"minimum coverage probability\", rather than the \"average probability\", with the nominal value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = x, n = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  x out of n, null probability 0.5\nX-squared = 2.2175, df = 1, p-value = 0.1365\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.4518087 0.5064898\nsample estimates:\n        p \n0.4790875 \n```\n\n\n:::\n:::\n\n\nFinally, there is the Clopper-Pearson **exact confidence interval**. Clopper-Pearson inverts two single-tailed binomial tests at the desired alpha. This is a non-trivial calculation, so there is no easy formula to crank through.  Just use the `binom.test()` function and pray no one asks for an explanation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(x = x, n = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  x and n\nnumber of successes = 630, number of trials = 1315, p-value = 0.1364\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.4517790 0.5064896\nsample estimates:\nprobability of success \n             0.4790875 \n```\n\n\n:::\n:::\n\n\nThe expected probability of no one being a high-risk drinker is $f(0;0.479) = \\frac{1315!}{0!(1315-0)!} 0.479^0 (1-0.479)^{1315-0} = 0$. Use `dbinom()` for probability densities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(x = 0, size = n, p = p)\n## [1] 0\n```\n:::\n\n\nThe expected probability of *at least* half the population being a high-risk drinker, $f(658, 0.479) = .065$. Use `pbinom()` for cumulative probabilities. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(q = .5 * n, size = n, prob = p, lower.tail = FALSE)\n## [1] 0.06455096\n```\n:::\n\n\nThe normal distribution is a good approximation when $n$ is large. The $\\lim_{n \\rightarrow \\infty} \\mathrm{Bin}(n, \\pi) = N(n\\pi, n\\pi(1−\\pi)).$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(q = 0.5, mean = p, sd = se, lower.tail = FALSE)\n## [1] 0.06450357\n```\n:::\n\n\nSuppose a second survey gets a slightly different result. The *high risk* = `Yes` falls from 630 (48%) to 600 (46%).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_bin2 <- data.frame(\n  subject = 1:1315,\n  high_risk = factor(c(rep(\"Yes\", 600), rep(\"No\", 715)))\n)\n(dat2_tabyl <- janitor::tabyl(dat_bin2, high_risk))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n high_risk   n   percent\n        No 715 0.5437262\n       Yes 600 0.4562738\n```\n\n\n:::\n:::\n\n\nThe two survey counts of *high risk* = \"Yes\" are independent random variables distributed $X \\sim \\mathrm{Bin}(1315, .48)$ and $Y \\sim \\mathrm{Bin}(1315, .46)$. What is the probability that either variable is $X \\ge 650$?\n\nLet $P(A) = P(X \\le 650)$ and $P(B) = P(Y \\le 650)$. Then $P(A|B) = P(A) + P(B) - P(AB)$, and because the events are independent, $P(AB) = P(A)P(B)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(p_a <- pbinom(q = 650, size = 1315, prob = 0.48, lower.tail = FALSE))\n## [1] 0.1433791\n(p_b <- pbinom(q = 650, size = 1315, prob = 0.46, lower.tail = FALSE))\n## [1] 0.005868366\n(p_a + p_b - (p_a * p_b))\n## [1] 0.1484061\n```\n:::\n\n\nHere's an empirical test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(\n  x = rbinom(10000, 1315, 0.48),\n  y = rbinom(10000, 1315, 0.46)\n)\nmean(if_else(df$x >= 650 | df$y >= 650, 1, 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1619\n```\n\n\n:::\n:::\n\n\nA couple other points to remember:\n\n* The Bernoulli distribution is a special case of the binomial with $n = 1$. \n* The binomial distribution assumes independent trials. If you sample *without replacement from a finite population*, use the hypergeometric distribution.\n\n## Hypergeometric\n\n> If $X = k$ is the count of successful events in a sample of size $n$ *without replacement* from a population of size $N$ containing $K$ successes, then $X$ is a random variable with a hypergeometric distribution\n>\n> $$f_X(k|N, K, n) = \\frac{{{K}\\choose{k}}{{N-K}\\choose{n-k}}}{{N}\\choose{n}}.$$\n>\n> with $E(X)=n\\frac{K}{N}$ and $Var(X) = n\\frac{K}{N}\\cdot\\frac{N-k}{N}\\cdot\\frac{N-n}{N-1}$.  \n\nThe formula follows from the frequency table of the possible outcomes.\n\n|           |Sampled |Not Sampled |Total |\n|-----------|--------|------------|------|\n|success    |k       |K-k         |K     |\n|non-success|n-k     |(N-K)-(n-k) |N-K   |\n|Total      |n       |N-n         |N     |\n\nHere is a simple analysis of data from a hypergeometric process. What is the probability of selecting $k = 14$ red marbles from a sample of $n = 20$ taken from an urn containing $K = 70$ red marbles and $N-K = 30$ green marbles?\n\nFunction `choose()` returns the binomial coefficient ${{n}\\choose{k}} = \\frac{n!}{k!(n-k)!}$.\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 14\nn <- 20\nN <- 100\nK <- 70\nchoose(K, k) * choose(N - K, n - k) / choose(N, n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2140911\n```\n\n\n:::\n:::\n\n\nBut of course you would never have to do it that way.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndhyper(x = k, m = K, n = N - K, k = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2140911\n```\n\n\n:::\n:::\n\n\nThe expected value is 14 and variance is 9.7292929. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe hypergeometric random variable is similar to the binomial random variable except that it applies to situations of sampling *without* replacement from a small population.  As the population size increases, sampling without replacement converges to sampling *with* replacement, and the hypergeometric distribution converges to the binomial. What if the total population size had been 250? 500? 1000?\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- data.frame(x = 1:20) %>%\n  mutate(density = dbinom(x = 1:20, size = n, prob = K / N)) %>%\n  ggplot() +\n  geom_col(aes(x = x, y = density))\nhyper <- data.frame(\n  x = 1:20,\n  N_100 = dhyper(x = 1:20, m = K * 1.0, n = (N - K) * 1.0, k = n),\n  N_250 = dhyper(x = 1:20, m = K * 2.5, n = (N - K) * 2.5, k = n),\n  N_500 = dhyper(x = 1:20, m = K * 5.0, n = (N - K) * 5.0, k = n)\n) %>%\n  pivot_longer(-x)\np +\n  geom_line(data = hyper, aes(x = x, y = value, color = name)) +\n  labs() +\n  theme_minimal() +\n  theme(legend.position = \"top\") +\n  labs(\n    title = \"P(X = k) when X ~ Hypergeometric(N, .7N, 20)\",\n    color = \"\",\n    x = \"k\"\n  )\n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## Poisson\n\nPoisson distributions are used to model the number of events occurring in a fixed period of time. In Poisson processes, events occur continuously and independently at a constant average rate. [This blog](https://towardsdatascience.com/poisson-distribution-intuition-and-derivation-1059aeab90d) by Aerin Kim demonstrates how the Poisson distribution is related to the binomial distribution. The key is that the binomial distribution expresses the probability of $X = k$ events in $n$ trials when the probability of *one* event in *one* trial is $p$. Sometimes you don't know $p$, but instead know that $\\lambda$ events occur per some time interval. You could try to back into the binomial by shrinking the time interval so that $k$ could never be greater than one. The ratio $p = \\lambda / n$ approaches the probability of observing one event in one trial as $n \\rightarrow \\infty$. As $n \\rightarrow \\infty$, $p \\rightarrow 0$. If you do this and follow the math, you wind up with the Poisson distribution!\n\n$$\\begin{eqnarray}\nP(X = k) &=& \\mathrm{lim}_{n \\rightarrow \\infty} {n \\choose k}p^k(1-p)^{n-k}\\\\\n&=& \\mathrm{lim}_{n \\rightarrow \\infty} \\frac{n!}{(n-k)!k!} \\left(\\frac{\\lambda}{n}\\right)^k \\left(1-\\frac{\\lambda}{n}\\right)^{n-k}\\\\\n&=& \\mathrm{lim}_{n \\rightarrow \\infty} \\frac{n!}{(n-k)!k!} \\left(\\frac{\\lambda}{n}\\right)^k \\left(1-\\frac{\\lambda}{n}\\right)^n\\left(1-\\frac{\\lambda}{n}\\right)^{-k}\\\\\n&=& \\mathrm{lim}_{n \\rightarrow \\infty} \\frac{n!}{(n-k)!k!} \\left(\\frac{\\lambda}{n}\\right)^k \\left(e^{-\\lambda}\\right)(1)\\\\\n&=& \\mathrm{lim}_{n \\rightarrow \\infty} \\frac{n!}{(n-k)!n^k}  e^{-\\lambda}\\frac{\\lambda^k}{k!} \\\\\n&=& e^{-\\lambda}\\frac{\\lambda^k}{k!}\n\\end{eqnarray}$$\n\nI didn't get that last step, but I'll take it on faith.\n\n> If $X$ is the number of successes in $n$ (many) trials when the probability of success $\\lambda / n$ is small, then $X$ is a random variable with a Poisson distribution $X \\sim \\mathrm{Pois}(\\lambda)$ \n>\n>$$f(X = k;\\lambda) = \\frac{e^{-\\lambda} \\lambda^k}{k!} \\hspace{1cm} k \\in (0, 1, ...), \\hspace{2mm} \\lambda > 0$$\n>\n>with $E(X)=\\lambda$ and $\\mathrm{Var}(X) = \\lambda$.\n\nThe Poisson distribution is also related to the exponential distribution. If the number of events per unit time follows a Poisson distribution, then the amount of time between events follows the exponential distribution.\n\nThe Poisson likelihood function is\n\n$$L(\\lambda; k) = \\prod_{i=1}^N f(k_i; \\lambda) = \\prod_{i=1}^N \\frac{e^{-\\lambda} \\lambda^k_i}{k_i !} = \\frac{e^{-n \\lambda} \\lambda^{\\sum k_i}}{\\prod k_i}.$$\n\nThe Poisson loglikelihood function is\n\n$$l(\\lambda; k) = \\sum_{i=1}^N k_i \\log \\lambda - n \\lambda.$$\n\nThe loglikelihood function is maximized at \n\n$$\\hat{\\lambda} = \\sum_{i=1}^N k_i / n.$$\n\nThus, for a Poisson sample, the MLE for $\\lambda$ is just the sample mean.\n\nConsider data set `dat_pois` containing frequencies counts of goals scored per match during a soccer tournament. Totals ranged from 0 to 8.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  goals freq\n1     0   23\n2     1   37\n3     2   20\n4     3   11\n5     4    2\n6     5    1\n7     6    0\n8     7    0\n9     8    1\n```\n\n\n:::\n:::\n\n\nThe MLE of $\\lambda$ is the sample weighted mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(lambda <- weighted.mean(dat_pois$goals, dat_pois$freq))\n## [1] 1.378947\n```\n:::\n\n\nThe 0.95 CI is $\\lambda \\pm z_{.05/2} \\sqrt{\\lambda / n}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- sum(dat_pois$freq)\nz <- qnorm(0.975)\nse <- sqrt(lambda / n)\nlambda + c(-z*se, +z*se)\n## [1] 1.142812 1.615082\n```\n:::\n\n\nThe expected probability of scoring 2 goals in a match is $\\frac{e^{-1.38} 1.38^2}{2!} = 0.239$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(x = 2, lambda = lambda)\n## [1] 0.2394397\n```\n:::\n\n\nThe expected probability of scoring 2 to 4 goals in a match is\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppois(q = 4, lambda = lambda) - \n  ppois(q = 1, lambda = lambda)\n## [1] 0.3874391\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(events = 0:10, \n           pmf = dpois(0:10, lambda), \n           cdf = ppois(0:10, lambda, lower.tail = TRUE)) %>%\nggplot() +\n  geom_col(aes(x = factor(events), y = pmf)) +\n  geom_text(aes(x = factor(events), label = round(pmf, 3), y = pmf + 0.01),\n            position = position_dodge(0.9), size = 3, vjust = 0) +\n  geom_line(aes(x = events, y = cdf/2), size = 1) +\n  scale_y_continuous(limits = c(0, .5), \n                     sec.axis = sec_axis(~ . * 2, name = \"Cum Prob\")) +\n  labs(title = \"PMF and CDF of Poisson Distribution\",\n       subtitle = paste0(\"Pois(\", scales::comma(lambda, accuracy = .01), \")\"), \n       x = \"X = k\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nHow well does the Poisson distribution fit the `dat_pois` data set?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_pois %>%\n  mutate(pred = n * dpois(x = goals, lambda = lambda)) %>%\n  rename(obs = freq) %>%\n  pivot_longer(cols = -goals) %>%\n  ggplot(aes(x = goals, y = value, color = name)) +\n  geom_point() +\n#  geom_smooth(se = FALSE) +\n  theme(legend.position = \"top\") +\n  labs(\n    title = \"Poisson Dist: Observed vs Expected\",\n    color = \"\",\n    y = \"frequencey\"\n  )\n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nIt seems to fit pretty good! Run a chi-square goodness-of-fit test to confirm. The test requires an expected frequency of at least 5 per cell. Cells 4 through 8 are under 5, so you need to lump them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- dat_pois %>% \n  group_by(goals = if_else(goals >= 4, 4, goals)) %>% \n  summarize(.groups = \"drop\", freq = sum(freq)) %>% \n  pull(freq)\np <- dat_pois %>% \n  mutate(p = dpois(x = goals, lambda = lambda)) %>%\n  group_by(goals = if_else(goals >= 4, 4, goals)) %>% \n  summarize(.groups = \"drop\", p = sum(p)) %>% \n  pull(p)\n(chisq_test <- chisq.test(x = x, p = p, rescale.p = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  x\nX-squared = 1.0414, df = 4, p-value = 0.9035\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n> A chi-square goodness-of-fit test was conducted to determine whether the matches had the same proportion of goals as the theoretical Poisson distribution. The minimum expected frequency was 5. The chi-square goodness-of-fit test indicated that the number of matches with 0, 1, 2, 3, or 4 or more goals was *not* statistically significantly different from the proportions expected in the theoretical Poisson distribution ($\\chi^2$(4) = 1.041, *p* = 0.903).\n\nAs demonstrated at the beginning of this section, the $\\mathrm{Pois}(\\lambda)$ approaches the $\\mathrm{Bin}(n, \\pi)$ where $\\lambda = n\\pi$ when $n \\rightarrow \\infty$ and $\\pi \\rightarrow 0$. The Poisson is a useful (computationally inexpensive) approximation to the binomial when $n \\ge 20)$ and $\\pi \\le 0.05$. For example, suppose a baseball player has a $\\pi = .03$ chance of hitting a home run. What is the probability of hitting $X \\ge 20$ home runs in $n = 500$ at-bats? This is a binomial process because the sample size is fixed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(q = 20, size = 500, prob = 0.03, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07979678\n```\n\n\n:::\n:::\n\n\nBut $n$ is large and $\\pi$ is small, so the Poisson distribution works well too.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppois(q = 20, lambda = 0.03 * 500, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08297091\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 500\np = 0.03\nx = 0:30\ndata.frame(\n  events = x, \n  Poisson = dpois(x = x, lambda = p * n),\n  Binomial = dbinom(x = x, size = n, p = p)\n) %>%\n  pivot_longer(cols = -events) %>%\n  ggplot(aes(x = events, y = value, color = name)) +\n  geom_line() +\n  theme(legend.position = \"top\") +\n  labs(title = \"Pois(.03*500) vs. Bin(500, .03)\",\n       subtitle = \"Poisson approximation to binomial.\",\n       x = \"Events\",\n       y = \"Density\",\n       color = \"\")\n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nWhen the observed variance is greater than $\\lambda$ (overdispersion), the Negative Binomial distribution can be used instead of Poisson.\n\n## Exponential\n\nExponential distributions are usually used to model the elapsed time between events in a Poisson process. \n\n> If $X$ is the time to the next successful event in a Poisson process where the average rate of events is $\\lambda$, then $X$ is a random variable with an exponential distribution $X \\sim  \\mathrm{Exp}(\\lambda)$ \n>\n> $$ f(X = x; \\lambda) = \n\\begin{cases} \n\\lambda e^{-\\lambda x}, & \\mbox{if } x \\ge 0 \\\\ \n0, & \\mbox{if } x < 0 \n\\end{cases} $$\n>\n>with $E(X)=1/\\lambda$ and $Var(X) = 1/\\lambda^2$.  \n\n[This blog](https://towardsdatascience.com/what-is-exponential-distribution-7bdd08590e2a) by Aerin Kim demonstrates how the exponential distribution is related to the Poisson distribution. The key is that the probability of *no* event in 1 time period is $P(X = 0; \\lambda) = e^{-\\lambda}\\frac{\\lambda^0}{0!} = e^{-\\lambda}$, so the probability of no events in *t* time periods is $P(X>t) =e^{-\\lambda t}$ because the $t$ periods are independent. The CDF is $P(X \\le t) =1 - e^{-\\lambda t}$. And the PDF is its derivative, $P(X = t) = \\lambda e^{-\\lambda t}$\n\nKim shows how the exponential distribution is \"memory-less\", meaning the $P(X > x_1 | X > x_0) = P(X > x_1 - x_0).$ E.g., the probability a 9-year old machine fails after 12 years is the same as the probability a 0-year old machine fails after 3 years. If that seems like a bad model, turn to something with increasing hazard rates, like Weibull. But oftentimes it *is* a good assumption, like the probability of a car accident (this is the context in which you might refer to $\\lambda$ as the hazard rate).\n\nSuppose the average rate of bus arrivals is one per 15 minutes, a Poisson process. The probability less than 10 minutes elapses between buses is $P(X \\le 10) = 1 - e^{-1/15 \\cdot 10} = .486.$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(min = 0:60) %>% mutate(p = pexp(min, 1/15)) %>%\n  ggplot(aes(x = min)) +\n  geom_line(aes(y = p)) +\n  geom_hline(yintercept = pexp(10, 1/15), linetype = 2) +\n  geom_vline(xintercept = 10, linetype = 2) +\n  scale_y_continuous(breaks = seq(0, 1, .1)) +\n  scale_x_continuous(breaks = seq(0, 60, 5)) +\n  theme(panel.grid.minor = element_blank()) +\n  labs(title = \"P(X<=10) = .486\")\n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n90% of buses arrive within 34.5 minutes. \n \n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(min = 0:60) %>% mutate(p = pexp(min, 1/15)) %>%\n  ggplot(aes(x = min)) +\n  geom_line(aes(y = p)) +\n  geom_hline(yintercept = 0.90, linetype = 2) +\n  geom_vline(xintercept = qexp(.90, 1/15), linetype = 2) +\n  scale_y_continuous(breaks = seq(0, 1, .1)) +\n  scale_x_continuous(breaks = seq(0, 60, 5)) +\n  theme(panel.grid.minor = element_blank()) +\n  labs(title = \"P(X<=34.5) = .90\")\n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nThe average time for two buses to arrive is $2 \\cdot E[X] = 2 \\cdot \\frac{1}{1/15} = 30$ minutes.\n\n## Gamma\n\nGamma distributions are usually used to model wait times until events. Unlike the exponential distribution which models the time until the first event, gamma models the time until the $\\alpha$th or $k$th event.\n\nBefore you learn about the gamma distribution, you should understand the gamma *function*, $\\Gamma(n) = (n-1)!$, because it is part of the definition. $\\Gamma(n)$ extends the factorial from nonnegative whole numbers to a subset of the real numbers. The generalization of the factorial is used in combinatorics and probability problems. Some probability distributions are defined in terms of the gamma function, including the student *t*, chi-square, and gamma distribution.\n\nThe gamma distribution is a two-parameter distribution. You will encounter two forms of the gamma distribution.\n\n* **shape** $k$ and **scale** $\\theta$.\n* **shape** $\\alpha = k$ and **rate** $\\beta = 1/\\theta$.\n\nThe probability density function for the shape $k$ and scale $\\theta$ form is\n\n> If $X$ is the interval until the $k^{th}$ successful event when the average interval is $\\theta$, then $X$ is a random variable with a gamma distribution $X \\sim \\mathrm{\\Gamma}(k, \\theta)$. The probability of an interval of $X = x$ is\n>\n>$$f(x; k, \\theta) = \\frac{x^{k-1} e^{-\\frac{x}{\\theta}}}{\\theta^k \\Gamma(k)} \\hspace{1cm} x, k, \\theta > 0.$$\n>\n> with $E(X) = k \\theta$ and variance $Var(X) = k \\theta^2$.  \n\nThe probability density function for the shape $\\alpha$ and rate $\\beta$ form is\n\n> If $X$ is the interval until the $\\alpha^{th}$ successful event when events occur at a rate of $\\beta$ times per interval, then $X$ is a random variable with a gamma distribution $X \\sim \\mathrm{\\Gamma}(\\alpha, \\beta)$. The probability of an interval of $X = x$ is\n>\n> $$f(x; \\alpha, \\beta) = \\frac{\\beta^\\alpha x^{\\alpha-1}e^{-\\beta x}}{\\Gamma(\\alpha)} \\hspace{1cm} x, \\alpha, \\beta > 0.$$\n>\n> with $E(X) = \\alpha / \\beta$ and variance $Var(X) = \\alpha / \\beta^2$.\n\nGamma is the conjugate prior to the Poisson, exponential, normal, Pareto, and gamma likelihood distributions.\n\n**Example**. On average, someone sends a money order once per 15 minutes. What is the probability someone sends 10 money orders in less than 3 hours? The shape/scale formulation is $x = 3$, $k = 10$, and $\\theta = .25$ hours elapsed per event. The shape/rate formulation is $x = 3$, $\\alpha = 10$, and $\\beta = 4$ events per hour. In `pgamma()` below, just remember that scale is the inverse of rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(p <- pgamma(q = 3, shape = 10, scale = 0.25))\n## [1] 0.7576078\n\ntibble(\n  x = seq(0, 10, by = .1),\n  prob = pgamma(q = x, shape = 10, scale = .25, lower.tail = TRUE)\n) %>%\n  ggplot() +\n  geom_line(aes(x = x, y = prob)) +\n  geom_segment(aes(x = 3, xend = 3, y = 0, yend = p), linetype = 2) +\n  geom_segment(aes(x = 0, xend = 3, y = p, yend = p), linetype = 2) +\n  scale_x_continuous(breaks = 0:10) +\n  scale_y_continuous(breaks = c(0, p, 1), labels = percent_format(1)) +\n  theme(panel.grid.minor = element_blank()) +\n  labs(title = \"Prob. of 10 events in 3 hrs when mean time to event is .25 hrs.\",\n       x = \"Interval (x) (hours)\", y = \"pgamma\") \n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nReferences: [Arein Kim](https://towardsdatascience.com/gamma-distribution-intuition-derivation-and-examples-55f407423840).\n\n## Beta\n\nThe beta distribution, $\\mathrm{Beta}(\\alpha, \\beta)$, is a family of distributions used to model probabilities. In Bayesian inference, it is frequently the conjugate prior distribution for the Bernoulli, binomial, negative binomial, and geometric distributions. When the beta distribution is used as the conjugate prior, the posterior distribution is also a beta distribution, greatly reducing the complexity of the analysis. After accumulating additional evidence, you simply adjust the $\\alpha$ and $\\beta$ parameters.\n\n> If $P$ is the probability of success in a random process then $P$ may be expressed as a random variable with a beta distribution $P \\sim \\mathrm{Beta}(\\alpha, \\beta)$. The probability that $P = p$ is\n>\n> $$f(p; \\alpha, \\beta) = \\frac{p^{\\alpha-1} (1-p)^{\\beta-1}}{\\mathrm{B}(\\alpha, \\beta)}, \\hspace{1cm} \\mathrm{B}(\\alpha, \\beta) = \\frac{\\Gamma(\\alpha) \\Gamma(\\beta)}{\\Gamma(\\alpha + \\beta)}.$$\n>\n> with $E(X) = \\frac{\\alpha}{\\alpha + \\beta}$.\n\nThe $\\mathrm{B}(\\alpha, \\beta)$ is a normalization constant that causes the pdf to integrate to 1 over the range of $p$, $\\int_0^1f(p)dp = 1.$\n\n$\\mathrm{Beta}(1, 1)$ expresses a uniform probability density, the expression of complete ignorance of the correct prior distribution. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(p = seq(0, 1, .01)) %>%\n  mutate(Beta = dbeta(p, 1, 1)) %>%\n  ggplot(aes(x = p, y = Beta)) +\n  geom_line() +\n  labs(title = \"Beta(1, 1) is the uniform probability density.\")\n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n$\\mathrm{Beta}(5, 5)$ is a symmetric probability; $\\mathrm{Beta}(10, 10)$ is also symmetric, but with smaller variance. In general, the strength of the prior increases with the sum of $\\alpha + \\beta$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nThe distribution shifts to the left if $\\beta$ > $\\alpha$ and right if $\\alpha$ > $\\beta$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nIf one of the values is < 1, the curve flips toward $\\infty$ at the extreme. $\\alpha$ or $\\beta$ is usually 0.5 to denote near certainty.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n## Normal\n\nUnder the central limit theorem, if we take samples from a random variable and calculate a summary statistic for each sample, that statistic is itself a random variable, and its mean converges to the true population statistic with more and more sampling.\n\nThe standard deviation of a sampled statistic is called the *standard error* of that statistic. In the case of the sampled mean, it is \n\n$$SE = \\frac{\\sigma}{\\sqrt{n}}$$\n\n## Student t\n\nThe *t*-distribution is essentially an approximation of the normal distribution acknowledging that we only have a sample estimate of the true population standard deviation in how we calculate the standard error.\n\n## Weibull\n\nWeibull distributions are used in time-to-event models.\n\n> If $X$ is the time to failure in a process in which the failure rate is proportional to a power of time defined by shape $k$ and scale $\\lambda$ parameters, then $X$ is a random variable with a Weibull distribution $X \\sim  \\mathrm{WB}(k, \\lambda)$ \n> \n> $$ f(X = x; k, \\lambda) = \\begin{cases} \n\\frac{k}{\\lambda} \\left(\\frac{x}{\\lambda}\\right)^{k-1} e^{-(x / \\lambda)^k}, & x \\ge 0 \\\\\n0, & x < 0\n\\end{cases}$$\n\n$k$ is called the *hazard rate*. If *k* < 1 the failure rate decreases over time, as is the case with significant infant mortality or defective items. If *k* = 1 the failure rate is constant, as when external event cause failure. If *k* > 1 the failure rate accelerates, as with aging processes.\n\nThere are several alternative parameterizations ([Wikipedia](https://en.wikipedia.org/wiki/Weibull_distribution)). The common one for survival analysis replaces the scale parameter with a rate parameter $\\beta = 1 / \\lambda$. Then for *x* $\\ge$ 0, \n\n$$f(X = x; k, \\beta) = \\beta k (\\beta x)^{k-1} e^{-(\\beta x)^k}$$\nwith cumulative distribution function\n$$F(x; k, \\beta) = 1 - e^{-(\\beta x)^k}$$\nand hazard function \n$$h(x; k, \\beta) = \\beta k (\\beta x)^{k-1}.$$\n\nThe \"survival curve\" is the compliment to the CDF: \n$$\\begin{eqnarray}\nS(x; k, \\beta) &=& 1 - F(x; k, \\beta) \\\\\n&=& e^{-(\\beta x)^k}\n\\end{eqnarray}$$\n\nThe probability of failing at time $x = t$ is the probability of surviving to time time multiplied by the hazard of failing when $x = t$, $f(t; k, \\beta) = S(t; k, \\beta) \\cdot h(t; k, \\beta)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpand.grid(x = seq(from = .05, to = 2.5, by = .01),\n                   k = c(.5, 1, 1.5, 5)) %>%\n  mutate(f = dweibull(x, k),\n         F = pweibull(x, k),\n         S = pweibull(x, k, lower.tail = FALSE),\n         h = f / S) %>%\n  pivot_longer(cols = c(f:h)) %>%\n  ggplot(aes(x = x, y = value, color = factor(k))) +\n  geom_line() +\n  facet_wrap(vars(name), scales = \"free_y\") +\n  scale_colour_hue(h = c(90, 270)) +\n  theme(legend.position = \"top\") +\n  labs(x = NULL, y = NULL, color = \"k\", title = \"Weibull (lambda = 1))\")\n```\n\n::: {.cell-output-display}\n![](prob_distr_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nMore [here](https://www.weibull.com/basics/lifedata.htm).\n",
    "supporting": [
      "prob_distr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}